#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Sep 28 16:45:10 2008

import wx,os

# begin wxGlade: extracode
#import wx.propgrid as wxpg

from hex import HexView

# end wxGlade



class PeachMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PeachMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.peachMainSplitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.peachMainSplitter, -1)
        self.window_1_pane_1 = wx.Panel(self.peachMainSplitter, -1)
        
        # Tool Bar
        self.peachMainToolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.peachMainToolbar)
        self.peachMainToolbar.AddLabelTool(6001, "New", wx.Bitmap("icons\\document-new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Create new Peach XML file", "")
        self.peachMainToolbar.AddLabelTool(6002, "Open", wx.Bitmap("icons\\document-open.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Open Peach XML File (Ctrl-O)", "")
        self.peachMainToolbar.AddLabelTool(6003, "Save", wx.Bitmap("icons\\document-save.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Save file (Ctrl-S)", "")
        self.peachMainToolbar.AddLabelTool(6004, "Save As...", wx.Bitmap("icons\\document-save-as.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Save file as...", "")
        self.peachMainToolbar.AddSeparator()
        self.peachMainToolbar.AddLabelTool(6007, "Copy", wx.Bitmap("icons\\edit-copy.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Copy current element (Ctrl-C)", "")
        self.peachMainToolbar.AddLabelTool(6008, "Cut", wx.Bitmap("icons\\edit-cut.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Cut current element (Ctrl-X)", "")
        self.peachMainToolbar.AddLabelTool(6009, "Past", wx.Bitmap("icons\\edit-paste.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Paste current element (Ctrl-V)", "")
        self.peachMainToolbar.AddSeparator()
        self.peachMainToolbar.AddLabelTool(6010, "New Node", wx.Bitmap("icons\\list-add.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Add a new element (Insert)", "")
        self.peachMainToolbar.AddLabelTool(6011, "Remove Node", wx.Bitmap("icons\\list-remove.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Remove current element (Delete)", "")
        self.peachMainToolbar.AddSeparator()
        self.peachMainToolbar.AddLabelTool(6012, "Up", wx.Bitmap("icons\\go-up.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Move element up (Ctrl-UP)", "")
        self.peachMainToolbar.AddLabelTool(6013, "Down", wx.Bitmap("icons\\go-down.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Move element down (Ctrl-Down)", "")
        self.peachMainToolbar.AddSeparator()
        self.peachMainToolbar.AddLabelTool(6014, "Test", wx.Bitmap("icons\\applications-system.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Test DDL (Ctrl-T)", "")
        self.peachMainToolbar.AddSeparator()
        self.peachMainToolbar.AddLabelTool(6015, "About", wx.Bitmap("icons\\about.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "About...", "")
        # Tool Bar end
        self.peachMainTree = wx.TreeCtrl(self.window_1_pane_1, -1, style=wx.TR_HAS_BUTTONS|wx.TR_LINES_AT_ROOT|wx.TR_EDIT_LABELS|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.textTreeHelp = wx.TextCtrl(self.window_1_pane_1, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_WORDWRAP)
        self.peachMainPropertyGrid = wxpg.PropertyGrid(self.window_1_pane_2, -1)
        self.textPropHelp = wx.TextCtrl(self.window_1_pane_2, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_WORDWRAP)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.OnToolbarNew, id=6001)
        self.Bind(wx.EVT_TOOL, self.OnToolbarOpen, id=6002)
        self.Bind(wx.EVT_TOOL, self.OnToolbarSave, id=6003)
        self.Bind(wx.EVT_TOOL, self.OnToolbarSaveAs, id=6004)
        self.Bind(wx.EVT_TOOL, self.OnToolbarCopy, id=6007)
        self.Bind(wx.EVT_TOOL, self.OnToolbarCut, id=6008)
        self.Bind(wx.EVT_TOOL, self.OnToolbarPast, id=6009)
        self.Bind(wx.EVT_TOOL, self.OnToolbarNewNode, id=6010)
        self.Bind(wx.EVT_TOOL, self.OnToolbarRemoveNode, id=6011)
        self.Bind(wx.EVT_TOOL, self.OnToolbarUp, id=6012)
        self.Bind(wx.EVT_TOOL, self.OnToolbarDown, id=6013)
        self.Bind(wx.EVT_TOOL, self.OnToolbarTest, id=6014)
        self.Bind(wx.EVT_TOOL, self.OnToolbarAbout, id=6015)
        self.Bind(wx.EVT_TREE_END_DRAG, self.OnTreeEndDrag, self.peachMainTree)
        self.Bind(wx.EVT_TREE_DELETE_ITEM, self.OnTreeDeleteItem, self.peachMainTree)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnTreeSelectionChanged, self.peachMainTree)
        self.Bind(wx.EVT_TREE_SEL_CHANGING, self.OnTreeSelectionChanging, self.peachMainTree)
        self.Bind(wx.EVT_TREE_ITEM_ACTIVATED, self.OnTreeItemActivated, self.peachMainTree)
        self.Bind(wx.EVT_TREE_END_LABEL_EDIT, self.OnTreeEndLabelEdit, self.peachMainTree)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PeachMainFrame.__set_properties
        self.SetTitle("Peach Builder")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap(os.path.join("icons", "peach20x20.ico"), wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.peachMainToolbar.Realize()
        self.peachMainTree.SetFocus()
        self.textTreeHelp.SetBackgroundColour(wx.Colour(249, 255, 191))
        self.textTreeHelp.Hide()
        self.textPropHelp.SetBackgroundColour(wx.Colour(249, 255, 191))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PeachMainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_6.Add(self.peachMainTree, 3, wx.EXPAND, 0)
        sizer_6.Add(self.textTreeHelp, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_2)
        sizer_5.Add(self.peachMainPropertyGrid, 3, wx.EXPAND, 0)
        sizer_5.Add(self.textPropHelp, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_3)
        self.peachMainSplitter.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_1.Add(self.peachMainSplitter, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnToolbarNew(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarNew' not implemented!"
        event.Skip()

    def OnToolbarOpen(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarOpen' not implemented!"
        event.Skip()

    def OnToolbarSave(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarSave' not implemented!"
        event.Skip()

    def OnToolbarSaveAs(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarSaveAs' not implemented!"
        event.Skip()

    def OnToolbarCopy(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarCopy' not implemented!"
        event.Skip()

    def OnToolbarCut(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarCut' not implemented!"
        event.Skip()

    def OnToolbarPast(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarPast' not implemented!"
        event.Skip()

    def OnToolbarNewNode(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarNewNode' not implemented!"
        event.Skip()

    def OnToolbarRemoveNode(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarRemoveNode' not implemented!"
        event.Skip()

    def OnToolbarUp(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarUp' not implemented!"
        event.Skip()

    def OnToolbarDown(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarDown' not implemented!"
        event.Skip()

    def OnToolbarTest(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarTest' not implemented!"
        event.Skip()

    def OnToolbarAbout(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnToolbarAbout' not implemented!"
        event.Skip()

    def OnTreeEndDrag(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeEndDrag' not implemented!"
        event.Skip()

    def OnTreeDeleteItem(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeDeleteItem' not implemented!"
        event.Skip()

    def OnTreeSelectionChanged(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeSelectionChanged' not implemented!"
        event.Skip()

    def OnTreeSelectionChanging(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeSelectionChanging' not implemented!"
        event.Skip()

    def OnTreeItemActivated(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeItemActivated' not implemented!"
        event.Skip()

    def OnTreeEndLabelEdit(self, event): # wxGlade: PeachMainFrame.<event_handler>
        print "Event handler `OnTreeEndLabelEdit' not implemented!"
        event.Skip()

# end of class PeachMainFrame


class AddDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Element Type:", style=wx.ALIGN_RIGHT)
        self.AddDialogListBox = wx.ListBox(self, -1, choices=["asdasd", "ASDASDASD", "AADSDASD", "asdasd", "asdasd", "AAAAAA"], style=wx.LB_SINGLE|wx.LB_NEEDED_SB|wx.LB_SORT)
        self.textAddHelp = wx.TextCtrl(self, -1, "AAAAAAAAAAAAAAAAAAAAAAAAAAAA", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.AddDialogOkButton = wx.Button(self, wx.ID_OK, "OK")
        self.AddDialogCancelButton = wx.Button(self, wx.ID_CANCEL, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.OnListBox, self.AddDialogListBox)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddDialog.__set_properties
        self.SetTitle("Add Element")
        self.AddDialogListBox.SetFocus()
        self.AddDialogListBox.SetSelection(0)
        self.textAddHelp.SetBackgroundColour(wx.Colour(249, 255, 191))
        self.AddDialogOkButton.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddDialog.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_5.Add(self.label_1, 0, wx.RIGHT, 0)
        sizer_8.Add(self.AddDialogListBox, 2, wx.EXPAND, 0)
        sizer_8.Add(self.textAddHelp, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(sizer_8, 1, wx.EXPAND, 0)
        grid_sizer_5.AddGrowableRow(0)
        grid_sizer_5.AddGrowableCol(1)
        sizer_7_copy_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.AddDialogOkButton, 0, 0, 0)
        grid_sizer_1.Add(self.AddDialogCancelButton, 0, 0, 0)
        sizer_7_copy_1.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_7_copy_1.AddGrowableRow(0)
        sizer_7_copy_1.AddGrowableCol(0)
        sizer_7.Add(sizer_7_copy_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def OnListBox(self, event): # wxGlade: AddDialog.<event_handler>
        print "Event handler `OnListBox' not implemented!"
        event.Skip()

# end of class AddDialog


class AboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("C:\\Peach\\Peach\\Gui\\icons\\big-peach.jpg", wx.BITMAP_TYPE_ANY))
        self.label_2 = wx.StaticText(self, -1, "\n  Peach Builder v1.0 BETA  \n\n       Copyright (c) 2007 Michael Eddington       \n\nhttp://peachfuzz.sf.net\n", style=wx.ALIGN_CENTRE)
        self.button_1 = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle("About Peach Builder")
        self.button_1.SetFocus()
        self.button_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        grid_sizer_2 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_4_copy = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2.Add(self.bitmap_1, 0, 0, 0)
        grid_sizer_2.Add(self.label_2, 0, wx.EXPAND, 0)
        sizer_4_copy.Add(self.button_1, 1, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(sizer_4_copy, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_2)
        grid_sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AboutDialog


class PeachTestDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PeachTestDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.buttonParse = wx.Button(self, -1, "Parse")
        self.buttonCount = wx.Button(self, -1, "Count")
        self.buttonGenerate = wx.Button(self, -1, "Generate")
        self.textOutput = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL)
        self.buttonDone = wx.Button(self, wx.ID_OK, "Done")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnParse, self.buttonParse)
        self.Bind(wx.EVT_BUTTON, self.OnCount, self.buttonCount)
        self.Bind(wx.EVT_BUTTON, self.OnGenerate, self.buttonGenerate)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PeachTestDialog.__set_properties
        self.SetTitle("Test DDL")
        self.buttonParse.SetDefault()
        self.textOutput.SetMinSize((300, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PeachTestDialog.__do_layout
        grid_sizer_3 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.buttonParse, 0, 0, 0)
        sizer_4.Add(self.buttonCount, 0, 0, 0)
        sizer_4.Add(self.buttonGenerate, 0, 0, 0)
        grid_sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.textOutput, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.buttonDone, 0, 0, 0)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

    def OnParse(self, event): # wxGlade: PeachTestDialog.<event_handler>
        print "Event handler `OnParse' not implemented!"
        event.Skip()

    def OnCount(self, event): # wxGlade: PeachTestDialog.<event_handler>
        print "Event handler `OnCount' not implemented!"
        event.Skip()

    def OnGenerate(self, event): # wxGlade: PeachTestDialog.<event_handler>
        print "Event handler `OnGenerate' not implemented!"
        event.Skip()

# end of class PeachTestDialog


class PeachValidation(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PeachValidation.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.splitterTopBottom = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.splitterTopBottom, -1)
        self.splitterRightLeft = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_2 = wx.Panel(self.splitterRightLeft, -1)
        self.notebook_1 = wx.Notebook(self.window_2_pane_2, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.window_2_pane_1 = wx.Panel(self.splitterRightLeft, -1)
        self.window_1_pane_1 = wx.Panel(self.splitterTopBottom, -1)
        self.label_6 = wx.StaticText(self.window_1_pane_1, -1, "Peach XML File:")
        self.textPeachXmlFilename = wx.TextCtrl(self.window_1_pane_1, -1, "")
        self.buttonPeachFileBrowse = wx.Button(self.window_1_pane_1, -1, "Browse...")
        self.buttonPeachFileLoad = wx.Button(self.window_1_pane_1, -1, "Load")
        self.label_7 = wx.StaticText(self.window_1_pane_1, -1, "Data Model:")
        self.comboDataModel = wx.ComboBox(self.window_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.static_line_1 = wx.StaticLine(self.window_1_pane_1, -1)
        self.label_3 = wx.StaticText(self.window_1_pane_1, -1, "Data file to load:")
        self.static_line_5 = wx.StaticLine(self.window_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.label_8 = wx.StaticText(self.window_1_pane_1, -1, "Select Mutator To Test:")
        self.textFilename = wx.TextCtrl(self.window_1_pane_1, -1, "")
        self.buttonBrowse = wx.Button(self.window_1_pane_1, -1, "Browse...")
        self.static_line_6 = wx.StaticLine(self.window_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.comboMutator = wx.ComboBox(self.window_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.buttonLoad = wx.Button(self.window_1_pane_1, -1, "Validate")
        self.static_line_7 = wx.StaticLine(self.window_1_pane_1, -1, style=wx.LI_VERTICAL)
        self.buttonGenerate = wx.Button(self.window_1_pane_1, -1, "Mutate")
        self.treeDataTree = wx.TreeCtrl(self.window_2_pane_1, -1, style=wx.TR_HAS_BUTTONS|wx.TR_LINES_AT_ROOT|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.textOutput = wx.TextCtrl(self.notebook_1_pane_1, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.hexView = HexView(self.notebook_1_pane_2)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnButtonPeachFileBrowse, self.buttonPeachFileBrowse)
        self.Bind(wx.EVT_BUTTON, self.OnButtonPeachXmlLoad, self.buttonPeachFileLoad)
        self.Bind(wx.EVT_COMBOBOX, self.OnComboDataModel, self.comboDataModel)
        self.Bind(wx.EVT_BUTTON, self.OnButtonBrowse, self.buttonBrowse)
        self.Bind(wx.EVT_BUTTON, self.OnButtonLoad, self.buttonLoad)
        self.Bind(wx.EVT_BUTTON, self.OnButtonGenerate, self.buttonGenerate)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnTreeSelChanged, self.treeDataTree)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PeachValidation.__set_properties
        self.SetTitle("Peach Validation")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap(os.path.join("icons","peach20x20.ico"), wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.textPeachXmlFilename.SetMinSize((150, 23))
        self.textPeachXmlFilename.SetFocus()
        self.textFilename.SetMinSize((150, 23))
        self.comboMutator.SetMinSize((200, 21))
        self.textOutput.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.textOutput.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Courier New"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PeachValidation.__do_layout
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_6 = wx.FlexGridSizer(4, 3, 3, 3)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_4 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_4.Add(self.label_6, 0, wx.ALL, 3)
        sizer_16.Add(self.textPeachXmlFilename, 0, wx.EXPAND, 0)
        sizer_16.Add(self.buttonPeachFileBrowse, 0, wx.LEFT|wx.RIGHT, 3)
        sizer_16.Add(self.buttonPeachFileLoad, 0, 0, 0)
        grid_sizer_4.Add(sizer_16, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_7, 0, wx.ALL, 3)
        grid_sizer_4.Add(self.comboDataModel, 0, wx.ALL|wx.EXPAND, 3)
        sizer_17.Add(grid_sizer_4, 0, wx.ALL|wx.EXPAND, 2)
        sizer_17.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_6.Add(self.label_3, 0, wx.ALL, 3)
        grid_sizer_6.Add(self.static_line_5, 0, wx.EXPAND, 0)
        grid_sizer_6.Add(self.label_8, 0, 0, 0)
        sizer_14.Add(self.textFilename, 1, wx.EXPAND, 0)
        sizer_14.Add(self.buttonBrowse, 0, wx.LEFT, 3)
        grid_sizer_6.Add(sizer_14, 1, wx.ALL|wx.EXPAND, 2)
        grid_sizer_6.Add(self.static_line_6, 0, wx.EXPAND, 0)
        grid_sizer_6.Add(self.comboMutator, 1, wx.EXPAND, 0)
        grid_sizer_6.Add(self.buttonLoad, 0, wx.ALL, 3)
        grid_sizer_6.Add(self.static_line_7, 0, wx.EXPAND, 0)
        grid_sizer_6.Add(self.buttonGenerate, 0, 0, 0)
        sizer_17.Add(grid_sizer_6, 0, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_17)
        sizer_12.Add(self.treeDataTree, 1, wx.EXPAND, 0)
        self.window_2_pane_1.SetSizer(sizer_12)
        sizer_10.Add(self.textOutput, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_10)
        sizer_13.Add(self.hexView, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(sizer_13)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Details")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Hex View")
        sizer_15.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.window_2_pane_2.SetSizer(sizer_15)
        self.splitterRightLeft.SplitVertically(self.window_2_pane_1, self.window_2_pane_2)
        sizer_11.Add(self.splitterRightLeft, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_11)
        self.splitterTopBottom.SplitHorizontally(self.window_1_pane_1, self.window_1_pane_2)
        sizer_9.Add(self.splitterTopBottom, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_9)
        sizer_9.Fit(self)
        self.Layout()
        # end wxGlade

    def OnButtonPeachFileBrowse(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnButtonPeachFileBrowse' not implemented!"
        event.Skip()

    def OnButtonPeachXmlLoad(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnButtonPeachXmlLoad' not implemented!"
        event.Skip()

    def OnComboDataModel(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnComboDataModel' not implemented!"
        event.Skip()

    def OnButtonBrowse(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnButtonBrowse' not implemented!"
        event.Skip()

    def OnButtonLoad(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnButtonLoad' not implemented!"
        event.Skip()

    def OnButtonGenerate(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnButtonGenerate' not implemented!"
        event.Skip()

    def OnTreeSelChanged(self, event): # wxGlade: PeachValidation.<event_handler>
        print "Event handler `OnTreeSelChanged' not implemented!"
        event.Skip()

# end of class PeachValidation


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    peachMain = PeachMainFrame(None, -1, "")
    app.SetTopWindow(peachMain)
    peachMain.Show()
    app.MainLoop()
